//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/html dojo/_base/array dojo/_base/fx dojo/on dojo/aspect jimu/BaseWidgetPanel jimu/BaseWidgetFrame jimu/utils ./FoldableDijit ./FoldableWidgetFrame".split(" "),function(p,h,b,e,v,l,q,r,s,f,t,u){function d(){return b.getMarginBox(jimuConfig.layoutId).w<=m?!0:!1}function k(){return b.getMarginBox(jimuConfig.layoutId).w<=m?"100%":360}var m=jimuConfig.widthBreaks[0],n=b.getMarginBox(jimuConfig.layoutId).h;return p([r,t],{baseClass:"jimu-widget-panel jimu-foldable-dijit jimu-foldable-panel",
closeTolerance:30,startup:function(){this.titleHeight=35;this.isFull=null;this.inherited(arguments);this.createCloseBtn();this.createFoldableBtn();this.resize()},getFullPosition:function(){var a={},b=this.position;a.left=b.left?b.left:"auto";a.right=b.right?b.right:"auto";a.top=b.top?b.top:"auto";a.bottom=b.bottom?b.bottom:"auto";a.width=b.width?b.width:"auto";a.height=b.height?b.height:"auto";this.isFull&&(a.right=0,a.bottom=0);return a},changePosition:function(){var a;this.position.width=k();this.isFull?
(b.place(this.domNode,jimuConfig.layoutId),a={left:0,right:0,top:0,bottom:0,width:"auto",height:"auto"}):(b.place(this.domNode,jimuConfig.mapId),a={left:this.position.left?this.position.left:"auto",right:this.position.right?this.position.right:"auto",top:this.position.top?this.position.top:"auto",bottom:this.position.bottom?this.position.bottom:"auto",width:this.position.width?this.position.width:"auto",height:this.position.height?this.position.height:"auto"});b.setStyle(this.domNode,f.getPositionStyle(a));
f.setVerticalCenter(this.titleNode);this.setBorderRadius();this.moveTitle()},setBorderRadius:function(){b.setStyle(this.domNode,this.isFull?{borderTopLeftRadius:0,borderTopRightRadius:0,borderBottomLeftRadius:0,borderBottomRightRadius:0}:{borderTopLeftRadius:"4px",borderTopRightRadius:"4px",borderBottomLeftRadius:"4px",borderBottomRightRadius:"4px"})},_changePos:function(){this.position.width=k();d()||(this.position.left="auto");this.position.height="auto"},resize:function(){this._changePos();var a;
if(!(a=this.isFull!==d())){a=b.getMarginBox(jimuConfig.layoutId);var g=n!==a.h;n=a.h;a=g}a&&(this.isFull=d(),this.changePosition(),this.isFull?(b.addClass(this.foldableNode,"pack-down"),b.removeClass(this.foldableNode,"pack-up")):(b.removeClass(this.foldableNode,"pack-down"),b.addClass(this.foldableNode,"pack-up")));a=k();b.setStyle(this.domNode,{width:"number"===typeof a?a+"px":a});this.inherited(arguments);1<this.getChildren().length&&this._setFrameSize()},reloadWidget:function(a){this.inherited(arguments);
this.isWidgetInPanel(a)&&(Array.isArray(this.config.widgets)||this.setTitleLabel(a.label))},updateConfig:function(a){this.inherited(arguments);this.setTitleLabel(a.label)},_setFrameSize:function(){var a,g=b.getContentBox(this.containerNode),c=0;e.forEach(this.getChildren(),function(a){a.folded||c++},this);a=(g.h-(this.getChildren().length-c)*this.getChildren()[0].titleHeight)/c;console.log("box.h\x3d"+g.h+", h\x3d"+a);e.forEach(this.getChildren(),function(c){c.folded?b.setStyle(c.domNode,{height:c.titleHeight+
"px"}):b.setStyle(c.domNode,{height:a+"px"});c.resize()},this)},createCloseBtn:function(){this.isFull?this.closeNode=b.create("div",{"class":"fold-btn jimu-vcenter"},this.titleNode):(this.closeNode=b.create("div",{"class":"close-btn jimu-vcenter"},this.titleNode),this.own(l(this.closeNode,"click",h.hitch(this,function(a){a.stopPropagation();this.panelManager.closePanel(this)}))));f.setVerticalCenter(this.titleNode)},createFoldableBtn:function(){this.foldableNode=b.create("div",{"class":"foldable-btn jimu-vcenter"},
this.titleNode);this.own(l(this.foldableNode,"click",h.hitch(this,function(a){a.stopPropagation();this.onTitleClick()})))},createFrame:function(a){this.config.widgets&&1===this.config.widgets.length||!this.config.widgets?a=new s:(a=new u({label:a.label,widgetManager:this.widgetManager}),q.after(a,"onFoldStateChanged",h.hitch(this,function(){var a=0;this._setFrameSize();e.forEach(this.getChildren(),function(b){b.folded||a++},this);e.forEach(this.getChildren(),function(b){b.foldEnable=!b.folded&&1===
a?!1:!0},this)})));return a},createFullCloseTip:function(){return b.create("div",{"class":"close-tip",innerHTML:"Close",style:{height:this.titleHeight+"px",lineHeight:this.titleHeight+"px"}},this.domNode)},onTitleClick:function(){this.folded?(this.folded=!1,b.setStyle(this.domNode,f.getPositionStyle(this.getFullPosition())),this.moveTitle(),d()?(b.removeClass(this.foldableNode,"pack-up"),b.addClass(this.foldableNode,"pack-down")):(b.addClass(this.foldableNode,"pack-up"),b.removeClass(this.foldableNode,
"pack-down"))):(this.folded=!0,b.setStyle(this.domNode,{height:this.titleHeight+"px"}),this.moveTitle(),d()?(b.removeClass(this.foldableNode,"pack-down"),b.addClass(this.foldableNode,"pack-up")):(b.addClass(this.foldableNode,"pack-down"),b.removeClass(this.foldableNode,"pack-up")));this.onFoldStateChanged()},onOpen:function(){this.inherited(arguments);this._changePos();this.isFull=d();this.changePosition();if(this.folded)this.onTitleClick()},onFoldStateChanged:function(){e.forEach(this.getChildren(),
function(a){(a=a.getWidget())&&(this.folded?this.widgetManager.minimizeWidget(a):this.widgetManager.maximizeWidget(a))},this)},moveTitle:function(){this.isFull?this.folded?b.setStyle(this.domNode,{top:b.getMarginBox(jimuConfig.layoutId).h-this.titleHeight+"px"}):b.setStyle(this.domNode,{top:"0px"}):b.setStyle(this.domNode,{top:this.position.top+"px"})}})});