//>>built
require({cache:{"url:widgets/Geoprocessing/setting/SettingDetail.html":'\x3cdiv\x3e\n\t\x3cdiv class\x3d"nav-pane" data-dojo-attach-point\x3d"navPaneNode"\x3e\x3c/div\x3e\n\t\x3cdiv class\x3d"setting-pane" data-dojo-attach-point\x3d"settingPaneNode" style\x3d"display:none"\x3e\x3c/div\x3e\n\x3c/div\x3e\n'}});
define("dojo/_base/declare dojo/_base/lang dojo/_base/html dojo/_base/array dojo/on dojo/query dojo/text!./SettingDetail.html dijit/_WidgetBase dijit/_TemplatedMixin dijit/TitlePane esri/request jimu/dijit/ViewStack jimu/dijit/LoadingShelter jimu/dijit/Message ./ParamSetting ./LayerOrder ./Options ../utils".split(" "),function(h,d,b,g,f,k,l,m,n,p,q,r,s,t,u,v,w,x){return h([m,n],{baseClass:"jimu-widget-setting-gp-detail",templateString:l,postCreate:function(){this.inherited(arguments);this.paramSetting=
new u({map:this.map,nls:this.nls});this.layerOrder=new v({nls:this.nls});this.options=new w({nls:this.nls});this.viewStack=new r({viewType:"dijit",views:[this.paramSetting,this.layerOrder,this.options]},this.settingPaneNode);this.loadingCover=new s({hidden:!0});this.loadingCover.placeAt(this.domNode);this.loadingCover.startup()},startup:function(){this.inherited(arguments);this.viewStack.startup()},setConfig:function(a){a=d.clone(a);this.hasInputParam=!0;this.config&&this.config.taskUrl===a.taskUrl?
(this.config=a,this._initNavPane()):(this.config=a,this.loadingCover.show(),q({url:this.config.taskUrl,content:{f:"json"},handleAs:"json",timeout:1E4}).then(d.hitch(this,function(a){this.loadingCover.hide();this._changeTaskInfoToConfig(a);this._initNavPane()})))},getConfig:function(){if(!this.config.taskUrl)return new t({message:this.nls.serviceURLPlaceholder}),!1;this.paramSetting.acceptValue();this.layerOrder.acceptValue();this.options.acceptValue();return this.config},_changeTaskInfoToConfig:function(a){var b=
this.config.taskUrl;this.config=a;this.config.taskUrl=b;this.config.isSynchronous="esriExecutionTypeSynchronous"===this.config.executionType?!0:!1;delete this.config.executionType;this.config.inputParams=[];this.config.outputParams=[];g.forEach(a.parameters,function(a){a.label=a.displayName;delete a.displayName;"esriGPParameterDirectionInput"===a.direction?this.config.inputParams.push(a):this.config.outputParams.push(a);delete a.direction;a.visible=!0;a.required="esriGPParameterTypeRequired"===a.parameterType?
!0:!1;delete a.parameterType;"GPFeatureRecordSetLayer"===a.dataType&&(a.featureSetMode="draw")},this);this.config.shareResults=x.allowShareResult(this.config);delete this.config.parameters},_initNavPane:function(){b.empty(this.navPaneNode);this._createParamsSection("input");this._createParamsSection("output");this._createLayerOrderNode();this._createOptionsNode();this.layerOrder.setConfig(this.config);this.options.setConfig(this.config);this.paramSetting.setInputParams(this.config.inputParams)},_onParamClick:function(a,
e,c){this._setActiveLinkNode(c.currentTarget);this.paramSetting.param&&this.paramSetting.acceptValue();"none"===b.getStyle(this.viewStack.domNode,"display")&&b.setStyle(this.viewStack.domNode,"display","");this.viewStack.switchView(this.paramSetting);this.paramSetting.setParam(a,e)},_setActiveLinkNode:function(a){k(".jimu-state-active",this.domNode).removeClass("jimu-state-active");b.addClass(a,"jimu-state-active")},_createParamsSection:function(a){var e=b.create("div",{"class":"nodes"});(new p({title:this.nls[a],
content:e,open:"input"===a})).placeAt(this.navPaneNode);var c="input"===a?this.config.inputParams:this.config.outputParams;"input"===a&&0===c.length&&(this.hasInputParam=!1);g.forEach(c,function(b,c){var d=this._createParamLinkNode(b,a,e);if(this.hasInputParam&&0===c&&"input"===a||!1===this.hasInputParam&&0===c&&"output"===a)d.click?d.click():f.emit(d,"click",{cancelable:!0,bubble:!0})},this)},_createParamLinkNode:function(a,e,c){c=b.create("div",{"class":"link-action-node param-node"},c);b.create("div",
{innerHTML:"\x3cspan\x3e"+this.nls.name+':\x3c/span\x3e\x3cspan style\x3d"margin-left: 2px"\x3e'+a.name+"\x3c/span\x3e"},c);b.create("div",{innerHTML:"\x3cspan\x3e"+this.nls.type+':\x3c/span\x3e\x3cspan style\x3d"margin-left: 2px"\x3e'+a.dataType+"\x3c/span\x3e"},c);b.create("div",{innerHTML:"\x3cspan\x3e"+this.nls.required+':\x3c/span\x3e\x3cspan style\x3d"margin-left: 2px"\x3e'+a.required+"\x3c/span\x3e"},c);this.own(f(c,"click",d.hitch(this,this._onParamClick,a,e)));return c},_createLayerOrderNode:function(){var a=
b.create("div",{"class":"link-action-node nav-pane-node layer-order-node",innerHTML:this.nls.layerOrder},this.navPaneNode);this.own(f(a,"click",d.hitch(this,function(){this._setActiveLinkNode(a);this.viewStack.switchView(this.layerOrder)})))},_createOptionsNode:function(){var a=b.create("div",{"class":"link-action-node nav-pane-node options-node",innerHTML:this.nls.options},this.navPaneNode);this.own(f(a,"click",d.hitch(this,function(){this._setActiveLinkNode(a);this.viewStack.switchView(this.options)})))}})});