//>>built
define("dojo/_base/declare dijit/_WidgetBase dojo/_base/lang dojo/_base/array dojo/_base/html dojo/on dojo/aspect dojo/Deferred dojo/promise/all dijit/form/NumberTextBox dijit/form/Select dijit/form/TextBox dijit/form/DateTextBox dijit/form/TimeTextBox esri/symbols/jsonUtils jimu/dijit/CheckBox jimu/dijit/URLInput ./editors/simpleEditors ./editors/FeatureSetEditorChooser ./editors/FeatureSetRendererEditor ./editors/FeatureSetResultEditor ./editors/SelectFeatureSetFromLayer".split(" "),function(A,
B,C,h,D,n,p,E,F,q,r,s,G,H,t,u,v,e,w,I,x,y){function z(a,d,b){if(a.editorName&&0>a.dataType.indexOf("GPMultiValue"))return a.editorName;if("input"===d)return"GPMultiValue:GPFeatureRecordSetLayer"===a.dataType?"UnsupportEditor":-1<a.dataType.indexOf("GPMultiValue")&&a.choiceList&&0<a.choiceList.length?"MultiValueChooser":-1<a.dataType.indexOf("GPMultiValue")&&(!a.choiceList||0===a.choiceList.length)?"MultiValueEditor":"GPLong"===a.dataType||"GPDouble"===a.dataType?"NumberTextBox":"GPString"===a.dataType?
a.choiceList&&0<a.choiceList.length?"Select":"TextBox":"GPBoolean"===a.dataType?"CheckBox":"GPLinearUnit"===a.dataType?"LinerUnitEditor":"GPDate"===a.dataType?"DateTimeEditor":"GPDataFile"===a.dataType?"ObjectUrlEditor":"GPRasterDataLayer"===a.dataType?"ObjectUrlEditor":"GPRecordSet"===a.dataType?"ObjectUrlEditor":"GPFeatureRecordSetLayer"===a.dataType?"setting"===b?"FeatureSetEditorChooser":"draw"===a.featureSetMode?"SelectFeatureSetFromDraw":"layers"===a.featureSetMode?"SelectFeatureSetFromLayer":
"url"===a.featureSetMode?"SelectFeatureSetFromUrl":"UnsupportEditor":"UnsupportEditor";a="GPFeatureRecordSetLayer"===a.dataType?"FeatureSetResultEditor":"ShowMessage";return a}var f={},k,g=[],l;f.createEditor=function(a,d,b){var c;d=z(a,d,b);b={param:a,map:k,nls:l,context:b,editorManager:f,style:{width:"100%"}};if("UnsupportEditor"===d)b.message="type "+a.dataType+" is not supported for now.",c=new e.UnsupportEditor(b);else if("ShowMessage"===d)b.message="GPRecordSet"===a.dataType?"table":"GPDataFile"===
a.dataType||"GPRasterDataLayer"===a.dataType?"link":"text",c=new e.UnsupportEditor(b);else if("MultiValueChooser"===d)c=new e.MultiValueChooser(b);else if("MultiValueEditor"===d)c=new e.MultiValueEditor(b);else if("NumberTextBox"===d)b.gEditor=new q({value:void 0===a.defaultValue?"":a.defaultValue}),c=new e.GeneralEditorWrapperEditor(b);else if("Select"===d)b.gEditor=new r({options:h.map(a.choiceList,function(a){return{label:a,value:a}}),value:void 0===a.defaultValue?"":a.defaultValue}),c=new e.GeneralEditorWrapperEditor(b);
else if("TextBox"===d)b.gEditor=new s({value:void 0===a.defaultValue?"":a.defaultValue}),c=new e.GeneralEditorWrapperEditor(b);else if("CheckBox"===d)b.gEditor=new u({checked:void 0===a.defaultValue?!1:a.defaultValue}),c=new e.GeneralEditorWrapperEditor(b);else if("LinerUnitEditor"===d)c=new e.LinerUnitEditor(b);else if("DateTimeEditor"===d)c=new e.DateTimeEditor(b);else if("URLInput"===d)b.gEditor=new v({value:void 0===a.defaultValue?"":a.defaultValue}),c=new e.GeneralEditorWrapperEditor(b);else if("ObjectUrlEditor"===
d)a.defaultValue&&"string"===typeof a.defaultValue&&(b.value=a.defaultValue),c=new e.ObjectUrlEditor(b);else if("SelectFeatureSetFromDraw"===d)if(void 0===a.defaultValue)b.message="No defaultValue property.",c=new e.UnsupportEditor(b);else{var m=a.defaultValue.geometryType.substr(12,a.defaultValue.geometryType.length).toLowerCase();b.types=[m];b.showClear=!0;a.symbol&&(b[m+"Symbol"]=t.fromJson(a.symbol));c=new e.SelectFeatureSetFromDraw(b)}else"SelectFeatureSetFromLayer"===d?(a.defaultValue&&a.defaultValue.geometryType&&
(b.geometryType=a.defaultValue.geometryType),a.defaultValue&&(b.value=a.defaultValue),c=new y(b)):"SelectFeatureSetFromUrl"===d?(b.querySetting=a.defaultValue,b.value=a.featureSetUrl,c=new e.SelectFeatureSetFromUrl(b)):"FeatureSetEditorChooser"===d?c=new w(b):"LayerFieldChooser"===d?(a.defaultValue&&(b.value=a.defaultValue),c=new e.LayerFieldChooser(b)):"FeatureSetResultEditor"===d?c=new x(b):"GetUrlObjectFromLayer"===d?(a.defaultValue&&(b.value=a.defaultValue),c=new e.GetUrlObjectFromLayer(b)):(b.message=
"wrong editorName."+d,c=new e.UnsupportEditor(b));a.editorDependParamName&&(c.dependParam=a.editorDependParamName);p.before(c,"destroy",function(){g.splice(g.indexOf(c),1)});c.dependParam&&h.forEach(g,function(a){a.param.name===c.dependParam&&c.update(a.getValue())});"SelectFeatureSetFromLayer"===d&&n(c,"change",function(){h.forEach(g,function(b){b.dependParam===a.name&&b.update(c.getValue())})});g.push(c);return c};f.setMap=function(a){k=a};f.setNls=function(a){l=a};return f});