//>>built
require({cache:{"widgets/Coordinate/_build-generate_module":function(){define(["dojo/text!./Widget.html","dojo/text!./css/style.css","dojo/i18n!./nls/strings","dojo/text!./config.json"],function(){})},"url:widgets/Coordinate/Widget.html":'\x3cdiv\x3e\n  \x3cdiv data-dojo-attach-point\x3d"coordinateBackground"\x3e\n    \x3cdiv data-dojo-attach-point\x3d"coordinateMenuContainer" style\x3d"display:none"\x3e\n      \x3cdiv data-dojo-attach-point\x3d"coordinateMenu"\x3e\x3c/div\x3e\n    \x3c/div\x3e\n    \x3cdiv data-dojo-attach-point\x3d"coordinateInfo" class\x3d"coordinate-info"\x3e${nls.loading}\x3c/div\x3e\n    \x3cdiv class\x3d"coordinate-foldable" data-dojo-attach-point\x3d"foldableNode"\x3e\x3c/div\x3e\n  \x3c/div\x3e\n\x3c/div\x3e',
"url:widgets/Coordinate/css/style.css":".jimu-widget-coordinate .coordinate-background{background-color: rgba(255,255,255,0.4); padding: 2px 5px 2px 5px; line-height: 20px; overflow: hidden;}.jimu-widget-coordinate .coordinate-background:hover{background-color: rgba(255,255,255,0.6);}.jimu-widget-coordinate .coordinate-info{float: left; padding-right: 15px;}.jimu-widget-coordinate .coordinate-foldable{background: url(images/unfold01.png) center no-repeat; width: 7px; height: 20px; float: right;}.jimu-widget-coordinate:hover .coordinate-foldable{background-image: url(images/unfold02.png);};",
"url:widgets/Coordinate/config.json":'{\n  "outputunit": "dms",\n  "spatialReferences": []\n}',"*now":function(n){n(['dojo/i18n!*preload*widgets/Coordinate/nls/Widget*["ar","cs","da","de","en","es","et","fi","fr","he","it","ja","ko","lt","lv","nb","nl","pl","pt-br","pt-pt","ro","ru","sv","th","tr","zh-cn","ROOT"]'])}}});
define("dojo/_base/declare dojo/_base/array dojo/_base/html dijit/_WidgetsInTemplateMixin esri/geometry/Point esri/SpatialReference jimu/BaseWidget jimu/utils dojo/_base/lang dojo/on dojo/number dojo/dom-style dojo/dom-class dojo/dom-construct dijit/DropDownMenu dijit/MenuItem dijit/CheckedMenuItem dojo/aspect dojo/Deferred esri/request esri/tasks/ProjectParameters esri/tasks/GeometryService esri/geometry/webMercatorUtils jimu/portalUtils esri/config libs/usng/usng jimu/SpatialReference/unitUtils".split(" "),function(n,
H,q,t,u,r,v,w,f,h,I,k,x,J,y,z,K,A,B,C,D,L,E,F,G,s,p){var m={INCHES:"Inches",FOOT:"Foot",FEET:"Foot",YARDS:"Yards",MILES:"Miles",NAUTICAL_MILES:"Nautical_Miles",MILLIMETERS:"Millimeters",CENTIMETERS:"Centimeters",METER:"Meter",METERS:"Meter",KILOMETERS:"Kilometers",DECIMETERS:"Decimeters",DEGREE:"Decimal_Degrees",DECIMAL_DEGREES:"Decimal_Degrees",DEGREE_MINUTE_SECONDS:"Degree_Minutes_Seconds",MGRS:"MGRS",USNG:"USNG"},l={esriCentimeters:"CENTIMETERS",esriDecimalDegrees:"DECIMAL_DEGREES",esriDegreeMinuteSeconds:"DEGREE_MINUTE_SECONDS",
esriDecimeters:"DECIMETERS",esriFeet:"FEET",esriInches:"INCHES",esriKilometers:"KILOMETERS",esriMeters:"METERS",esriMiles:"MILES",esriMillimeters:"MILLIMETERS",esriNauticalMiles:"NAUTICAL_MILES",esriPoints:"POINTS",esriUnknownUnits:"UNKNOWN",esriYards:"YARDS"};return n([v,t],{baseClass:"jimu-widget-coordinate",name:"Coordinate",popMenu:null,selectedWkid:null,selectedItem:null,selectedTfWkid:null,forward:!0,enableRealtime:!1,geoServiceUrl:null,_mapWkid:null,_configured:!1,startup:function(){this.inherited(arguments);
this.selectedWkid=this._mapWkid=102100===this.map.spatialReference.wkid?3857:this.map.spatialReference.wkid;!this.config.spatialReferences||!this.config.spatialReferences.length?q.setStyle(this.foldableNode,"display","none"):q.setStyle(this.foldableNode,"display","inline-block")},onOpen:function(){x.add(this.coordinateBackground,"coordinate-background");this.own(h(this.map,"mouse-move",f.hitch(this,this.onMouseMove)));this.own(h(this.map,"click",f.hitch(this,this.onMapClick)));this.own(h(this.coordinateBackground,
"mouseover",f.hitch(this,this.onMouseOver)));this.own(h(this.coordinateBackground,"mouseout",f.hitch(this,this.onMouseOut)));this.own(h(this.coordinateMenuContainer,"mouseover",f.hitch(this,this.onMouseOverMenu)));this.own(h(this.coordinateMenuContainer,"mouseout",f.hitch(this,this.onMouseOutMenu)));this._processData().then(f.hitch(this,function(a){this.initPopMenu(a)}),f.hitch(this,function(a){console.log(a)}))},_processData:function(){var a=new B,b=this.map.itemInfo.itemData.baseMap.baseMapLayers[0];
!this.config.spatialReferences||!this.config.spatialReferences.length?F.getUnits(this.appConfig.portalUrl).then(f.hitch(this,function(c){var d=b&&("BingMapsRoad"===b.type||"BingMapsHybrid"===b.type||"BingMapsAerial"===b.type),e=b&&"WebTiledLayer"===b.type;b&&b.url?C({url:b.url,handleAs:"json",callbackParamName:"callback",content:{f:"json"}}).then(f.hitch(this,function(b){var d=this._getUnconfiguredUnitOptions(b.units,c),e={wkid:b.spatialReference.latestWkid||b.spatialReference.wkid,label:"",outputUnit:d.outputUnit};
e.options={sameSRWithMap:!0,defaultUnit:l[b.units],isGeographicUnit:d.isGeographicUnit,isGeographicCS:d.isGeographicCS,isProjectUnit:d.isProjectUnit,isProjectedCS:d.isProjectedCS,unitRate:d.unitRate};this._configured=!1;a.resolve(e)}),f.hitch(this,function(b){console.error(b);a.reject(b)})):b&&("OpenStreetMap"===b.type||d||e)?(d=this._getUnconfiguredUnitOptions("esriMeters",c),e={wkid:3857,label:"",outputUnit:d.outputUnit},e.options={sameSRWithMap:!0,defaultUnit:l.esriMeters,isGeographicUnit:d.isGeographicUnit,
isGeographicCS:d.isGeographicCS,isProjectUnit:d.isProjectUnit,isProjectedCS:d.isProjectedCS,unitRate:d.unitRate},this._configured=!1,a.resolve(e)):a.reject(Error("no baseMap"))})):(this._configured=!0,a.resolve(this.config.spatialReferences));return a},_getUnconfiguredUnitOptions:function(a,b){var c=m[l[a]],d="",e=1,f="",g="",h="",k="";p.isProjectUnit(c)?(h=k=!0,f=g=!1,d="english"===b?m[l.esriFeet].toUpperCase():m[l.esriMeters].toUpperCase(),e=p.getUnitRate(m[l[a]].toUpperCase(),d)):p.isGeographicUnit(c)&&
(h=k=!1,f=g=!0,d=l[a].toUpperCase());return{outputUnit:d,unitRate:e,isGeographicUnit:g,isGeographicCS:f,isProjectUnit:k,isProjectedCS:h}},initPopMenu:function(a){this.popMenu=new y({},this.coordinateMenu);A.after(this.popMenu,"onItemClick",f.hitch(this,this.onClickMenu),!0);f.isArray(a)?(this.selectedWkid=parseInt(a[0].wkid,10),this.selectedTfWkid=a[0].transformationWkid&&parseInt(a[0].transformationWkid,10),this._addAllMenuItems()):(this.selectedWkid=parseInt(a.wkid,10),this.addMenuItem("",this.selectedWkid,
a.outputUnit,null,null,a.options));this.selectedItem=this.popMenu.getChildren()[0];this.canRealtimeShow(this.selectedWkid)?(this.enableRealtime=!0,this.coordinateInfo.innerHTML=this.nls.realtimeLabel):(this.enableRealtime=!1,this.coordinateInfo.innerHTML=this.nls.hintMessage);this.popMenu.startup()},_addAllMenuItems:function(){for(var a=this.config.spatialReferences.length,b=0;b<a;b++)this.addMenuItem(this.config.spatialReferences[b].label,this.config.spatialReferences[b].wkid,this.config.spatialReferences[b].outputUnit,
this.config.spatialReferences[b].transformationWkid,this.config.spatialReferences[b].transformForward,this.config.spatialReferences[b].options)},_isWebMercator:function(a){return 102100===parseInt(a,10)||3857===parseInt(a,10)},canRealtimeShow:function(a){a=4326===this._mapWkid&&this._isWebMercator(a)||this._isWebMercator(this._mapWkid)&&4326===parseInt(a,10);var b=this.selectedItem.get("options");return b&&b.sameSRWithMap||a?!0:!1},onClickMenu:function(a){this.selectedItem.set({label:this.getStatusString(!1,
this.selectedItem.params.name,this.selectedItem.params.wkid)});this.selectedWkid=parseInt(a.params.wkid,10);this.selectedTfWkid=a.params.tfWkid;this.forward=a.params.forward;a.set({label:this.getStatusString(!0,a.params.name,a.params.wkid)});this.selectedItem=a;this.canRealtimeShow(this.selectedWkid)?(this.enableRealtime=!0,this.coordinateInfo.innerHTML=this.nls.realtimeLabel):(this.enableRealtime=!1,this.coordinateInfo.innerHTML=this.nls.hintMessage)},getStatusString:function(a,b,c){var d="",e=this._mapWkid;
c=parseInt(c,10);d=a?"\x26nbsp;\x26nbsp;\x26bull;\x26nbsp;\x26nbsp;\x3cb\x3e"+d+b+"\x3c/b\x3e\x26nbsp;("+c+")":"\x26nbsp;\x26nbsp;\x26nbsp;\x26nbsp;\x26nbsp;\x26nbsp;"+d+b+"\x26nbsp;("+c+")";c===e&&(d+=this.nls.defaultLabel);return d},addMenuItem:function(a,b,c,d,e,f){var g=this.getStatusString(!1,a,b);this.selectedWkid===parseInt(b,10)&&(g=this.getStatusString(!0,a,b));a={label:g||"",name:a||"",wkid:b||"",outputUnit:c||"",tfWkid:d||"",options:f};a.tfWkid&&(a.forward=e);this.popMenu.addChild(new z(a))},
_toFormat:function(a){var b=isFinite(parseInt(this.config.decimalPlaces,10))?parseInt(this.config.decimalPlaces,10):3,c=(a.toString().split(".")[1]||"").length,d="",e=c<b?c:b;c<b&&(d=Array.prototype.join.call({length:b-c+1},"0"));a=a.toFixed(e)+d;return this.separator(a,b)},onProjectComplete:function(a,b){if(this.selectedWkid&&a===this.selectedWkid){var c=b[0],d=c.x,c=c.y,e=this.selectedItem.get("outputUnit"),f=this.selectedItem.get("options");"MGRS"===e||"USNG"===e?this._displayUsngOrMgrs(e,c,d):
f.isGeographicUnit?this._displayDegOrDms(e,c,d):this._displayProject(e,c,d);this.coordinateInfo.innerHTML+="  ("+this._unitToNls(e)+")"}},_unitToNls:function(a){var b=m[a.toUpperCase()];return this.nls[b]||this.nls[a]||a},onError:function(a){alert(a)},onMapClick:function(a){if(!this.enableRealtime&&this.selectedItem){a=new u(a.mapPoint.x,a.mapPoint.y,this.map.spatialReference);var b=new D,c=null,d=this.selectedItem.get("options");b.geometries=[a];d.isProjectedCS?c=d.isProjectUnit?this.selectedWkid:
d.spheroidCS:d.isGeographicCS&&(c=this.selectedWkid);this.selectedTfWkid&&(b.transformation=new r(parseInt(this.selectedTfWkid,10)),b.transformForward=JSON.parse(this.forward));b.outSR=new r(parseInt(c,10));this.coordinateInfo.innerHTML=this.nls.computing;console.log(b.toJson());G.defaults.geometryService.project(b,f.hitch(this,this.onProjectComplete,this.selectedWkid),f.hitch(this,this.onError))}},onMouseMove:function(a){if(this.enableRealtime&&this.selectedItem){var b=a.mapPoint;a=this.selectedItem.get("outputUnit");
var c=b.x,d=b.y,e=null,f=4326===this._mapWkid&&this._isWebMercator(this.selectedWkid)||this._isWebMercator(this._mapWkid)&&4326===this.selectedWkid,g=this.selectedItem.get("options"),e=b.normalize();g.isGeographicUnit&&(c=e.getLongitude()||c);g.isGeographicUnit&&(d=e.getLatitude()||d);if(f)4326===b.spatialReference.wkid&&this._isWebMercator(this.selectedWkid)?"MGRS"===a||"USNG"===a?this._displayUsngOrMgrs(a,e.getLatitude(),e.getLongitude()):g.isGeographicUnit?this._displayDegOrDms(a,d,c):g.isProjectUnit&&
(b=E.lngLatToXY(c,d),this._displayProject(a,b[1],b[0])):this._isWebMercator(b.spatialReference.wkid)&&4326===this.selectedWkid&&("MGRS"===a||"USNG"===a?this._displayUsngOrMgrs(a,e.getLatitude(),e.getLongitude()):g.isGeographicUnit&&this._displayDegOrDms(a,d,c));else{if(g.defaultUnit===a){this.coordinateInfo.innerHTML="X: "+this._toFormat(c)+",  Y: "+this._toFormat(d);this.coordinateInfo.innerHTML+="  ("+this._unitToNls(a)+")";return}4326===b.spatialReference.wkid||b.spatialReference.isWebMercator()?
"MGRS"===a||"USNG"===a?this._displayUsngOrMgrs(a,e.getLatitude(),e.getLongitude()):g.isGeographicUnit?this._displayDegOrDms(a,d,c):g.isProjectedCS&&this._displayProject(a,d,c):g.isProjectedCS?(c*=g.unitRate,d*=g.unitRate,this.coordinateInfo.innerHTML="X: "+this._toFormat(c)+",  Y: "+this._toFormat(d)):g.isGeographicCS&&("MGRS"===a||"USNG"===a?this._displayUsngOrMgrs(a,d,c):g.isGeographicUnit&&this._displayDegOrDms(a,d,c))}this.coordinateInfo.innerHTML+="  ("+this._unitToNls(a)+")"}},_displayUsngOrMgrs:function(a,
b,c){"MGRS"===a?this.coordinateInfo.innerHTML=s.LLtoMGRS(b,c,5):"USNG"===a&&(this.coordinateInfo.innerHTML=s.LLtoUSNG(b,c,5))},_displayDegOrDms:function(a,b,c){var d="",e="",d=this.selectedItem.get("options");c*=d.unitRate;b*=d.unitRate;"DEGREE_MINUTE_SECONDS"===a?(d=this.degToDMS(b,"LAT"),e=this.degToDMS(c,"LON"),this.coordinateInfo.innerHTML="LON: "+e+",  LAT: "+d):this.coordinateInfo.innerHTML="LON: "+this._toFormat(c)+",  LAT: "+this._toFormat(b)},_displayProject:function(a,b,c){a=this.selectedItem.get("options");
c*=a.unitRate;b*=a.unitRate;this.coordinateInfo.innerHTML="X: "+this._toFormat(c)+",  Y: "+this._toFormat(b)},onMouseOver:function(){this._configured&&k.set(this.coordinateMenuContainer,"display","block")},onMouseOut:function(){k.set(this.coordinateMenuContainer,"display","none")},onMouseOverMenu:function(){k.set(this.coordinateMenuContainer,"display","block")},onMouseOutMenu:function(){k.set(this.coordinateMenuContainer,"display","none")},degToDMS:function(a,b){var c=Math.abs(a),d=Math.floor(c),
c=c-d,e=Math.floor(60*c),c=Math.floor(3600*(c-e/60));60===c&&(e++,c=0);60===e&&(d++,e=0);return d+"\x26deg;\x26nbsp;"+(10>e?"0"+e:e)+"\x26prime;\x26nbsp;"+(10>c?"0"+c:c)+"\x26Prime;\x26nbsp;"+("LAT"===b?0>a?"S":"N":0>a?"W":"E")},separator:function(a,b){return this.config.addSeparator&&JSON.parse(this.config.addSeparator)?w.localizeNumber(a,{places:b}):a}})});