//>>built
require({cache:{"url:widgets/LayerList/LayerListView.html":'\n\n\x3ctable class\x3d"layer-list-table"\x3e\n  \x3ctbody class\x3d"layers-list-body" data-dojo-attach-point\x3d"layerListTable"\x3e\x3c/tbody\x3e      \n\x3c/table\x3e\n'}});
define("dijit/_WidgetBase dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-construct dojo/dom-geometry dojo/on dojo/aspect dojo/query jimu/dijit/CheckBox ./PopupMenu dijit/_TemplatedMixin dojo/text!./LayerListView.html esri/dijit/Legend ./NlsStrings dojo/dom-attr dojo/dom-class dojo/dom-style".split(" "),function(t,u,k,r,f,z,n,A,l,v,w,x,y,B,C,s,g,h){return u([t,x],{templateString:y,_currentSelectedLayerRowNode:null,postCreate:function(){r.forEach(this.operLayerInfos.finalLayerInfos,function(a){this.drawListNode(a,
0,this.layerListTable,!0)},this)},drawListNode:function(a,b,c){0===a.newSubLayers.length?(a.layerNode=this.addLayerNode(a,b,c),this.config.showLegend?this.addLegendNode(a,b,a.layerNode.subNode):h.set(l(".showLegend-image",a.layerNode.currentNode)[0],"display","none")):(a.layerNode=this.addLayerNode(a,b,c),r.forEach(a.newSubLayers,k.hitch(this,function(b,c){this.drawListNode(c,b+1,a.layerNode.subNode)},b)))},addLayerNode:function(a,b,c){var d=f.create("tr",{"class":"jimu-widget-row layer-row ",layerTrNodeId:a.id},
c),e,g,m,l,p,q;e=f.create("td",{"class":"col col1"},d);for(m=0;m<b;m++)f.create("div",{"class":"begin-blank-div",innerHTML:""},e);q=f.create("div",{"class":"showLegend-div"},e);l=f.create("img",{"class":"showLegend-image",src:this.layerListWidget.folderUrl+"images/v_right.png",alt:"l"},q);g=f.create("div",{"class":"div-select"},e);m=new v({checked:a.isVisible()});f.place(m.domNode,g);p=f.create("div",{"class":"noLegend-div"},e);f.create("img",{"class":"noLegend-image",src:this.layerListWidget.folderUrl+
"images/noLegend.png",alt:"l"},p);a.noLegend?(h.set(q,"display","none"),h.set(g,"display","none")):h.set(p,"display","none");h.set(e,"width",12*b+35+"px");e=f.create("td",{"class":"col col2"},d);f.create("div",{innerHTML:a.title,"class":"div-content"},e);e=f.create("td",{"class":"col col3"},d);b=f.create("div",{"class":"layers-list-popupMenu-div"},e);e=(new w({items:a.popupMenuInfo.menuItems,box:this.layerListWidget.domNode.parentNode})).placeAt(b);this.own(n(e,"onMenuClick",k.hitch(this,this._onPopupMenuItemClick,
a,e)));c=f.create("tr",{"class":"",layerContentTrNodeId:a.id},c);c=f.create("td",{"class":"",colspan:"3"},c);c=f.create("table",{"class":"layer-sub-node"},c);this.own(n(d,"click",k.hitch(this,this._onRowTrClick,a,l,d)));this.own(n(d,"mouseover",k.hitch(this,this._onLayerNodeMouseover,d,e)));this.own(n(d,"mouseout",k.hitch(this,this._onLayerNodeMouseout,d,e)));this.own(n(m.domNode,"click",k.hitch(this,this._onCkSelectNodeClick,a,m)));this.own(n(b,"click",k.hitch(this,this._onPopupMenuClick,a,e,d)));
return{currentNode:d,subNode:c}},addLegendNode:function(a,b,c){c=f.create("tr",{"class":"legend-node-tr"},c);c=f.create("td",{"class":"legend-node-td"},c);try{var d=a.obtainLegendsNode();a.legendsNode=d;h.set(d,"marginLeft",12*(b+1)+"px");f.place(d,c)}catch(e){console.error(e)}},_fold:function(a,b){"none"===h.get(a.layerNode.subNode,"display")?(h.set(a.layerNode.subNode,"display","table"),s.set(b,"src",this.layerListWidget.folderUrl+"images/v.png")):(h.set(a.layerNode.subNode,"display","none"),s.set(b,
"src",this.layerListWidget.folderUrl+"images/v_right.png"))},_onImageShowLegendClick:function(a,b,c){this._fold(a,b);c&&c.stopPropagation()},_onCkSelectNodeClick:function(a,b,c){b.checked?a.setTopLayerVisible(!0):a.setTopLayerVisible(!1);c.stopPropagation()},_onPopupMenuClick:function(a,b,c,d){this._changeSelectedLayerRow(c);b&&"opened"===b.state?b.closeDropMenu():(this._hideCurrentPopupMenu(),b&&(a=a.getDeniedItems(),b.openDropMenu(a),this.currentPopupMenu=b));d.stopPropagation()},_hideCurrentPopupMenu:function(){this.currentPopupMenu&&
"opened"===this.currentPopupMenu.state&&this.currentPopupMenu.closeDropMenu()},_onLayerNodeMouseover:function(a,b){g.add(a,"layer-row-mouseover");b&&g.add(b.btnNode,"jimu-icon-btn-selected")},_onLayerNodeMouseout:function(a,b){g.remove(a,"layer-row-mouseover");b&&g.remove(b.btnNode,"jimu-icon-btn-selected")},_onPopupMenuHide:function(){console.log("aaa")},_onLayerListWidgetPaneClick:function(a){a&&a.closeDropMenu()},_onRowTrClick:function(a,b,c){this._changeSelectedLayerRow(c);this._onImageShowLegendClick(a,
b);a.loadLegends(this.layerListWidget.appConfig.portalUrl)},_changeSelectedLayerRow:function(a){this._currentSelectedLayerRowNode&&this._currentSelectedLayerRowNode===a||(this._currentSelectedLayerRowNode&&g.remove(this._currentSelectedLayerRowNode,"jimu-widget-row-selected"),g.add(a,"jimu-widget-row-selected"),this._currentSelectedLayerRowNode=a)},_onPopupMenuItemClick:function(a,b,c,d){d={itemKey:c.key,data:d,layerListWidget:this.layerListWidget,layerListView:this};"transparency"===c.key?"none"===
h.get(b.transparencyDiv,"display")?b.showTransNode(a.getOpacity()):b.hideTransNode():(a=a.onPopupMenuClick(d),a.closeMenu&&b.closeDropMenu())},_exchangeLayerTrNode:function(a,b){var c=l("tr[layerTrNodeId\x3d'"+a+"']",this.layerListTable)[0],d=l("tr[layerTrNodeId\x3d'"+b+"']",this.layerListTable)[0],e=l("tr[layerContentTrNodeId\x3d'"+b+"']",this.layerListTable)[0];this.layerListTable.removeChild(d);this.layerListTable.insertBefore(d,c);this.layerListTable.removeChild(e);this.layerListTable.insertBefore(e,
c)},moveUpLayer:function(a){var b=this.operLayerInfos.moveUpLayer(a);b&&this._exchangeLayerTrNode(b,a)},moveDownLayer:function(a){var b=this.operLayerInfos.moveDownLayer(a);b&&this._exchangeLayerTrNode(a,b)}})});