//>>built
require({cache:{"widgets/AttributeTable/utils":function(){define(["dojo/_base/lang","dojo/_base/array","jimu/LayerInfos/LayerInfos","dojo/Deferred","dojo/promise/all"],function(e,h,n,f,b){function p(a){var c=[],b=[];h.forEach(a,function(a){0>c.indexOf(a.name)?c.push(a.name):b.push(a)});h.forEach(b,function(a){a.name=a.name+"-"+a.id})}var l={readLayerInfosObj:function(a){return n.getInstance(a,a.itemInfo)},readLayerInfosFromMap:function(a){var c=new f;n.getInstance(a,a.itemInfo).then(e.hitch(this,
function(a){var b=[];a.traversal(e.hitch(this,function(a){b.push(a)}));c.resolve(b)}),e.hitch(this,function(a){console.error(a);c.reject(a)}));return c},readLayerObjectsFromMap:function(a){var c=new f,k=[];this.readLayerInfosFromMap(a).then(e.hitch(this,function(a){h.forEach(a,e.hitch(this,function(a){k.push(a.getLayerObject())}));b(k).then(e.hitch(this,function(a){c.resolve(a)}),e.hitch(this,function(a){c.reject(a);console.error(a)}))}),e.hitch(this,function(a){c.reject(a)}));return c},readConfigLayerInfosFromMap:function(a){var c=
new f,k=[];this.readLayerInfosFromMap(a).then(e.hitch(this,function(a){var f=[];h.forEach(a,function(a){k.push(a.getLayerType())});b(k).then(e.hitch(this,function(b){h.forEach(b,e.hitch(this,function(b,c){"FeatureLayer"===b&&(a[c].name=a[c].title,f.push(a[c]))}));p(f);c.resolve(f)}),e.hitch(this,function(a){c.reject(a)}))}),e.hitch(this,function(a){c.reject(a)}));return c},getConfigInfosFromLayerInfos:function(a){return h.map(a,function(a){return l.getConfigInfoFromLayerInfo(a)})},getConfigInfoFromLayerInfo:function(a){var b=
{};b.name=a.name;b.id=a.id;b.show=a.isShowInMap();b.layer={url:a.getUrl()};if((a=a.getPopupInfo())&&!a.description)b.layer.fields=h.map(a.fieldInfos,function(a){return{name:a.fieldName,alias:a.label.toLowerCase(),show:a.visible}});return b}};return l})},"widgets/AttributeTable/setting/_build-generate_module":function(){define(["dojo/text!./Setting.html","dojo/text!./css/style.css","dojo/i18n!./nls/strings"],function(){})},"url:widgets/AttributeTable/setting/Setting.html":'\x3cdiv style\x3d"width:100%;"\x3e\n  \x3cdiv data-dojo-attach-point\x3d"firstPage" class\x3d"first-page"\x3e\n    \x3cdiv data-dojo-attach-point\x3d"tableLayerInfos" class\x3d"table-layer-infos"\x3e\x3c/div\x3e\n    \x3cdiv data-dojo-attach-point\x3d"tableEditInfosError" style\x3d"display:none"\x3e\x3c/div\x3e\n    \x3cdiv style\x3d"margin: 10px;" data-dojo-attach-point\x3d"exportcsv" checked \n          data-dojo-type\x3d"jimu/dijit/CheckBox" label\x3d"${nls.exportCSV}"\x3e\x3c/div\x3e\n  \x3c/div\x3e\n\x3c/div\x3e\n',
"url:widgets/AttributeTable/setting/css/style.css":".jimu-widget-attributetable-setting{margin:0; padding:0; font-size:15px; width: 100%; height: 100%;}.jimu-widget-attributetable-setting .show{width: 120px;}.jimu-widget-attributetable-setting .symbol{width: 200px;}.jimu-widget-attributetable-setting .first-page{position: relative; height: 100%;}.jimu-widget-attributetable-setting .table-layer-infos{width: 100%; position: absolute; top: 0; bottom: 36px;}.jimu-widget-attributetable-setting .export-csv{margin: 10px; position: absolute; bottom: 0;}",
"*now":function(e){e(['dojo/i18n!*preload*widgets/AttributeTable/setting/nls/Setting*["ar","cs","da","de","en","es","et","fi","fr","he","it","ja","ko","lt","lv","nb","nl","pl","pt-br","pt-pt","ro","ru","sv","th","tr","zh-cn","ROOT"]'])}}});
define("dojo/_base/declare dijit/_WidgetsInTemplateMixin jimu/BaseWidgetSetting jimu/dijit/SimpleTable dojo/_base/lang dojo/_base/html dojo/_base/array dojo/on dojo/Deferred dojo/dom-style jimu/dijit/SymbolChooser dojo/query dojo/aspect esri/symbols/jsonUtils jimu/dijit/Message esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol jimu/dijit/CheckBox jimu/dijit/LoadingShelter ../utils dijit/TooltipDialog dijit/popup".split(" "),function(e,h,n,f,b,p,l,a,c,k,w,
r,x,y,s,z,A,B,C,t,q,u,m){return e([n,h],{baseClass:"jimu-widget-attributetable-setting",currentFieldTable:null,tooltipDialogs:{},fieldTables:{},_allLayerFields:null,_layerInfos:null,_delayedLayerInfos:null,startup:function(){this.inherited(arguments);this.config.layerInfos||(this.config.layerInfos=[]);this._allLayerFields=[];this._layerInfos=[];this._delayedLayerInfos=[];this.displayFieldsTable=new f({fields:[{name:"label",title:this.nls.label,type:"text"},{name:"url",title:"url",type:"text",hidden:!0},
{name:"index",title:"index",type:"text",hidden:!0},{name:"actions",title:this.nls.actions,type:"actions",actions:["edit"],"class":"symbol"},{name:"show",title:this.nls.show,type:"checkbox","class":"show"}],selectable:!1,autoHeight:!1});this.displayFieldsTable.placeAt(this.tableLayerInfos);p.setStyle(this.displayFieldsTable.domNode,{height:"100%"});this.displayFieldsTable.startup();this.shelter=new t({hidden:!0});this.shelter.placeAt(this.domNode.parentNode.parentNode||this.domNode);this.shelter.startup();
this.shelter.show();q.readLayerInfosObj(this.map).then(b.hitch(this,function(v){this.own(v.on("layerInfosChanged",b.hitch(this,this.onLayerInfosChanged)));this.own(a(this.displayFieldsTable,"actions-edit",b.hitch(this,this.editFieldsClick)));this.own(a(this.getParent().getParent().domNode,"click",b.hitch(this,function(){m.close()})));p.addClass(this.exportcsv.domNode,"export-csv");this.setConfig(this.config)}))},editFieldsClick:function(a){var d=r(".action-item-parent",a);if(d&&d.length)if(d=this.displayFieldsTable.getRowData(a),
d.show){var g=parseInt(d.index,10);this.shelter.show();this._getLayerFields(g).then(b.hitch(this,function(d){this.openFieldsDialog(a,d,g)}),b.hitch(this,function(a){console.error(a)})).always(b.hitch(this,function(){this.shelter.hide()}))}else var c=new s({message:this.nls.warning,buttons:[{label:this.nls.ok,onClick:b.hitch(this,function(){c.close()})}]})},_getLayerFields:function(a){var d=new c,g=this._allLayerFields[a];g?d.resolve(g):this._layerInfos[a].getLayerObject().then(b.hitch(this,function(a){a.fields?
d.resolve(a.fields):d.reject()}),b.hitch(this,function(a){d.reject(a)}));return d},openFieldsDialog:function(a,d,g){if(!this.tooltipDialogs[g]){var c=this._createFieldsTable(d,g);this.currentFieldTable=c;this.fieldTables[g]=c;d=new u({style:"width: 400px;height:400px;",content:c.domNode,onClose:b.hitch(this,function(){this._allLayerFields[g]=c.getData()}),onCancel:b.hitch(this,function(){m.close()})});this.tooltipDialogs[g]=d}a=r(".row-edit-div",a)[0];m.open({parent:this,popup:this.tooltipDialogs[g],
around:a,orient:["before-centered","below","below-alt","above","above-alt"]})},_createFieldsTable:function(a){for(var d=new f({fields:[{name:"show",title:this.nls.fieldVisibility,type:"checkbox","class":"show"},{name:"name",title:this.nls.fieldName,type:"text"},{name:"alias",title:this.nls.fieldAlias,editable:!0,type:"text"},{name:"actions",title:this.nls.fieldActions,type:"actions",actions:["up","down"],"class":"symbol"}],selectable:!1,autoHeight:!1,style:{height:"400px",maxHeight:"400px"}}),b=0;b<
a.length;b++)a[b].show=void 0===a[b].show?!0:!!a[b].show,d.addRow(a[b]);return d},setConfig:function(a){this.config=a;this.displayFieldsTable.clear();this._allLayerFields=[];this.tooltipDialogs={};this._processTableData().then(b.hitch(this,function(a){this._init(a);this.shelter.hide()}),b.hitch(this,function(a){new s({message:a.message||a})}))},onLayerInfosChanged:function(a,d,c){"added"===d&&c&&c.getLayerType().then(b.hitch(this,function(a){"FeatureLayer"===a&&(this._layerInfos&&0===this._layerInfos.length?
this._delayedLayerInfos.push(c):this._layerInfos&&(0<this._layerInfos.length&&!this._getLayerInfoById(c.id))&&(this._layerInfos.push(c),this.initConfigLayerInfos()))}))},_processDelayedLayerInfos:function(){0<this._delayedLayerInfos.length&&(l.forEach(this._delayedLayerInfos,b.hitch(this,function(a){this._getLayerInfoById(a.id)||this._layerInfos.push(a)})),this._delayedLayerInfos=[])},_processTableData:function(){var a=new c;q.readConfigLayerInfosFromMap(this.map).then(b.hitch(this,function(d){this._layerInfos=
d;this._processDelayedLayerInfos();this.config&&this.config.layerInfos&&0<this.config.layerInfos.length?(d=l.filter(this.config.layerInfos,b.hitch(this,function(a){return this._getLayerInfoById(a.id)})),a.resolve(d)):a.resolve(q.getConfigInfosFromLayerInfos(d))}),b.hitch(this,function(b){console.error(b);a.reject(b)}));return a},_init:function(a){for(var b=0;b<a.length;b++)this.displayFieldsTable.addRow({label:a[b].name,url:a[b].layer.url,index:""+b,show:a[b].show}),this._allLayerFields.push(a[b].layer.fields);
0===a.length?(k.set(this.tableEditInfosError,"display",""),this.tableEditInfosError.innerHTML=this.nls.noLayers):k.set(this.tableEditInfosError,"display","none");this.config.hideExportButton?this.exportcsv.uncheck():this.exportcsv.check()},_destroyPopupDialog:function(){m.close();for(var a in this.tooltipDialogs)this.tooltipDialogs[a]&&this.tooltipDialogs[a].destroy&&(this.tooltipDialogs[a].destroy(),this.tooltipDialogs[a]=null)},_getLayerInfoById:function(a){for(var b=0,c=this._layerInfos.length;b<
c;b++)if(this._layerInfos[b].id===a)return this._layerInfos[b]},getConfig:function(){m.close();for(var a=this.displayFieldsTable.getData(),b=[],c=a.length,e=0;e<c;e++){var f={};f.name=this._layerInfos[e].name;f.id=this._layerInfos[e].id;f.layer={};f.layer.url=a[e].url;f.layer.fields=this._allLayerFields[e];f.show=a[e].show;b.push(f)}this.config.layerInfos=b;this.exportcsv.getValue()?this.config.hideExportButton=!1:this.config.hideExportButton=!0;return this.config},destroy:function(){this._destroyPopupDialog();
this.inherited(arguments)}})});